"""
Word Document Generator Service
Generates Word documents with AI deal analysis
"""
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
import json


class WordGenerator:
    """Generate Word documents for deal analysis"""

    def __init__(self):
        """Initialize the Word generator"""
        pass

    def generate_analysis_report(self, deal_data):
        """
        Generate a comprehensive Word document with deal analysis

        Args:
            deal_data: Dictionary with deal information including AI analysis

        Returns:
            Document object ready to be saved
        """
        doc = Document()

        # Add title
        title = doc.add_heading('AI Deal Analysis Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add deal ID and date
        subtitle = doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        subtitle_run = subtitle.add_run(f"Deal #{deal_data.get('id')} | Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
        subtitle_run.font.size = Pt(10)
        subtitle_run.font.color.rgb = RGBColor(128, 128, 128)

        doc.add_paragraph()  # Spacer

        # Parse AI analysis
        ai_analysis = {}
        if deal_data.get('ai_analysis'):
            try:
                ai_analysis = json.loads(deal_data['ai_analysis'])
            except:
                ai_analysis = {}

        # AI Score Section
        self._add_score_section(doc, deal_data)

        # Basic Deal Information
        self._add_basic_info_section(doc, deal_data)

        # Executive Summary
        self._add_section(doc, '📊 Executive Summary',
                         ai_analysis.get('executive_summary', 'No summary available'))

        # Market Analysis
        self._add_section(doc, '📈 Market Analysis',
                         ai_analysis.get('market_analysis', 'No market analysis available'))

        # Origin Analysis
        self._add_section(doc, '🌍 Origin Analysis',
                         ai_analysis.get('origin_analysis', 'No origin analysis available'))

        # Buyer Profile
        self._add_section(doc, '👥 Buyer Profile & Market Fit',
                         ai_analysis.get('buyer_profile', 'No buyer profile available'))

        # Price Analysis
        self._add_section(doc, '💰 Price Competitiveness Analysis',
                         ai_analysis.get('price_analysis', 'No price analysis available'))

        # Payment & Logistics
        self._add_section(doc, '🚚 Payment & Logistics Assessment',
                         ai_analysis.get('payment_logistics', 'No logistics analysis available'))

        # Red Flags
        self._add_list_section(doc, '🚨 Red Flags & Concerns',
                              ai_analysis.get('red_flags', []))

        # Strengths
        self._add_list_section(doc, '✅ Deal Strengths',
                              ai_analysis.get('strengths', []))

        # Unusual Patterns
        self._add_list_section(doc, '🔍 Unusual Patterns',
                              ai_analysis.get('unusual_patterns', []))

        # Key Reasoning
        reasoning = []
        if deal_data.get('ai_reasoning'):
            try:
                reasoning = json.loads(deal_data['ai_reasoning']) if isinstance(deal_data['ai_reasoning'], str) else deal_data['ai_reasoning']
            except:
                reasoning = []
        self._add_list_section(doc, '💭 Key Reasoning', reasoning)

        # Next Steps
        self._add_list_section(doc, '📋 Recommended Next Steps',
                              ai_analysis.get('next_steps', []))

        # Raw Deal Text
        self._add_section(doc, '📄 Raw Deal Text',
                         deal_data.get('deal_text', 'No deal text available'))

        # Footer
        doc.add_page_break()
        footer = doc.add_paragraph()
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer_run = footer.add_run('This report was generated by AI and should be used for informational purposes only.\nAlways conduct proper due diligence before making trading decisions.')
        footer_run.font.size = Pt(9)
        footer_run.font.color.rgb = RGBColor(150, 150, 150)
        footer_run.italic = True

        return doc

    def _add_score_section(self, doc, deal_data):
        """Add the AI score section with styling"""
        heading = doc.add_heading('🤖 AI Assessment Score', level=1)

        score = deal_data.get('ai_score', 0)

        # Score paragraph
        score_para = doc.add_paragraph()
        score_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        score_run = score_para.add_run(f"{score}/100")
        score_run.font.size = Pt(36)
        score_run.font.bold = True

        # Determine risk level
        risk_level = 'medium'
        if score >= 70:
            risk_level = 'low'
            color = RGBColor(21, 87, 36)  # Green
        elif score < 50:
            risk_level = 'high'
            color = RGBColor(114, 28, 36)  # Red
        else:
            color = RGBColor(133, 100, 4)  # Yellow

        score_run.font.color.rgb = color

        # Risk level
        risk_para = doc.add_paragraph()
        risk_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        risk_run = risk_para.add_run(f"Risk Level: {risk_level.upper()}")
        risk_run.font.size = Pt(14)
        risk_run.font.bold = True
        risk_run.font.color.rgb = color

        # Recommendation
        ai_analysis = {}
        if deal_data.get('ai_analysis'):
            try:
                ai_analysis = json.loads(deal_data['ai_analysis'])
            except:
                pass

        recommendation = ai_analysis.get('recommendation', 'Review analysis carefully')
        if recommendation:
            rec_para = doc.add_paragraph()
            rec_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            rec_run = rec_para.add_run(f"\n{recommendation}")
            rec_run.font.size = Pt(11)
            rec_run.italic = True

        doc.add_paragraph()  # Spacer

    def _add_basic_info_section(self, doc, deal_data):
        """Add basic deal information"""
        doc.add_heading('📝 Deal Information', level=1)

        # Create a table for basic info
        table = doc.add_table(rows=8, cols=2)
        table.style = 'Light Grid Accent 1'

        # Format price
        if deal_data.get('price_type') == 'lme_discount':
            price_info = f"LME Discount - Gross: {deal_data.get('gross_discount')}%, Net: {deal_data.get('net_discount')}%"
        elif deal_data.get('price'):
            price_info = f"{deal_data.get('price')} {deal_data.get('price_currency', 'USD')}"
        else:
            price_info = "Not specified"

        # Fill table
        info_data = [
            ('Commodity', deal_data.get('commodity_type', 'N/A')),
            ('Source', f"{deal_data.get('source_name', 'N/A')} (Reliability: {deal_data.get('source_reliability', 'N/A')}/10)"),
            ('Price', price_info),
            ('Quantity', f"{deal_data.get('quantity', 'N/A')} {deal_data.get('quantity_unit', '')}"),
            ('Origin', deal_data.get('origin_country', 'Not specified')),
            ('Payment Method', deal_data.get('payment_method', 'Not specified')),
            ('Shipping Terms', deal_data.get('shipping_terms', 'Not specified')),
            ('Date Received', deal_data.get('date_received', 'N/A')),
        ]

        for i, (label, value) in enumerate(info_data):
            row = table.rows[i]
            label_cell = row.cells[0]
            value_cell = row.cells[1]

            label_cell.text = label
            value_cell.text = str(value)

            # Bold the labels
            label_cell.paragraphs[0].runs[0].font.bold = True

        doc.add_paragraph()  # Spacer

    def _add_section(self, doc, title, content):
        """Add a section with heading and content"""
        doc.add_heading(title, level=1)

        if content:
            # Split into paragraphs
            paragraphs = content.split('\n\n')
            for para_text in paragraphs:
                if para_text.strip():
                    para = doc.add_paragraph(para_text.strip())
                    para.paragraph_format.space_after = Pt(12)
        else:
            doc.add_paragraph('No information available')

        doc.add_paragraph()  # Spacer

    def _add_list_section(self, doc, title, items):
        """Add a section with a bulleted list"""
        doc.add_heading(title, level=1)

        if items and len(items) > 0:
            for item in items:
                doc.add_paragraph(str(item), style='List Bullet')
        else:
            doc.add_paragraph('None identified', style='List Bullet')

        doc.add_paragraph()  # Spacer
